name: "FieldCompare"
description: "Compare the fields in two files or two folders of files"
inputs:
  result:
    description: "The file/folder with the results to compare."
    required: True
  reference:
    description: "The file/folder with the references to compare the results against."
    required: True
  cli-options:
    description: "Pass fieldcompare command-line-interface options as string, e.g. for setting fuzzy tolerances."
    required: False
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.result }}
    - ${{ inputs.reference }}
    - ${{ inputs.cli-options }}
branding:
  icon: 'check-square'
  color: 'green'
